//! A JSON / OpenDesign HTML driven UI parser plugin for Bevy.
//!
//! `bevy_ai_ui_parser` lets a Bevy game load UI generated by Open Design or a
//! compatible BUI JSON file and run it as native Bevy UI. The intended game-UI
//! contract is:
//!
//! - OD or a tool exports `index.html` plus an `Asset/` directory.
//! - HTML/CSS describes layout, image-backed visuals, stable node ids, and
//!   `data-*` control semantics.
//! - Optional `<script type="application/json" data-bui-actions>` or static
//!   `window.BUI_ACTIONS = {...}` declares engine-readable prototype actions.
//! - Parser-generated focus order, value controls, and selection controls map
//!   browser-like input into Bevy ECS messages and state updates.
//! - Bevy game code owns business behavior through ECS systems and
//!   [`BuiActionAppExt::add_bui_action_handler`].
//!
//! # Loading HTML at runtime
//!
//! ```no_run
//! # use bevy_app::App;
//! # use bevy_ai_ui_parser::AiUiPlugin;
//! let mut app = App::new();
//! app.add_plugins(AiUiPlugin::from_html_path("ui/main_menu/index.html"));
//! ```
//!
//! # Registering game-side action handlers
//!
//! ```no_run
//! # use bevy_app::App;
//! # use bevy_ai_ui_parser::{AiUiPlugin, BuiActionAppExt};
//! let mut app = App::new();
//! app.add_plugins(AiUiPlugin::from_html_path("ui/main_menu/index.html"))
//!     .add_bui_action_handler("game.start_matchmaking", |world, event| {
//!         // Update ECS resources, change state, play sound, etc.
//!         let _ = (world, event);
//!     });
//! ```
//!
//! # Updating bound UI state from ECS
//!
//! ```no_run
//! # use bevy_app::{App, Update};
//! # use bevy_ecs::prelude::*;
//! # use bevy_ai_ui_parser::{BuiBindingValue, BuiStateSet};
//! fn update_status(mut writer: MessageWriter<BuiStateSet>) {
//!     writer.write(BuiStateSet {
//!         key: "race.status".to_string(),
//!         value: BuiBindingValue::Text("READY".to_string()),
//!     });
//! }
//! let mut app = App::new();
//! app.add_systems(Update, update_status);
//! ```
//!
//! See `README.md` for the full API guide, and `opendesign-integration/API.md`
//! for the Open Design integration contract.

mod core;

pub use core::model::{
    BuiActionBinding, BuiBinding, BuiBoxShadowConfig, BuiContent, BuiDocument, BuiImageConfig,
    BuiInteractionModel, BuiInteractionStep, BuiLayout, BuiNode, BuiNodeType, BuiResources,
    BuiScrollViewSemantics, BuiSemantics, BuiSliderSemantics, BuiStageFitSemantics, BuiStateModel,
    BuiStateVisual, BuiStyle, BuiStyles, BuiTextConfig, BuiTextShadowConfig, BuiTextureAtlasConfig,
    BuiTextureSlicerConfig, BuiVisuals,
};
pub use core::runtime::components::{BuiDocumentResource, BuiIdMap, BuiSourcePaths};
pub use core::runtime::plugin::{spawn_bui_ir, BuiPanelAppExt, BuiPanelPaths, BuiPanelSwitch};
pub use core::runtime::spawn::{spawn_bui_child, spawn_bui_tree};
pub use core::{
    opendesign_html_file_to_bui_json, opendesign_html_file_to_bui_json_with_manifest,
    opendesign_html_to_bui_json_str, opendesign_html_to_bui_json_str_with_manifest,
    validate_bui_json_file, validate_bui_json_str, AiUiPlugin, BuiActionAppExt, BuiActionRegistry,
    BuiActionTrigger, BuiActionTriggered, BuiBindingUpdate, BuiBindingValue, BuiDisabled, BuiId,
    BuiLogicTags, BuiRootEntity, BuiStateSet, BuiStateStore, BuiTextInput, BuiToggle,
    BuiVisualState,
};
